releases{
11
}

release:11{
DeleteDirectory:C:\SnipeIT
CreateDirectory:C:\SnipeIT
DownloadFile:Newtonsoft.Json.dll,C:\SnipeIT
DownloadFile:Newtonsoft.Json.xml,C:\SnipeIT
DownloadFile:RestSharp.dll,C:\SnipeIT
DownloadFile:Snipe_Agent.application,C:\SnipeIT
DownloadFile:Snipe_Agent.exe,C:\SnipeIT
DownloadFile:Snipe_Agent.exe.config,C:\SnipeIT
DownloadFile:Snipe_Agent.exe.manifest,C:\SnipeIT
DownloadFile:Snipe_Agent.pdb,C:\SnipeIT
DownloadFile:SnipeSharp.dll,C:\SnipeIT
DownloadFile:System.ValueTuple.dll,C:\SnipeIT
DownloadFile:System.ValueTuple.xml,C:\SnipeIT
}